# Preparation of schrut dataset
https://towardsdatascience.com/python-text-analysis-with-the-schrutepy-package-234bc70f3916

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# pip install schrutepy

In [3]:
from schrutepy import schrutepy 

In [4]:
df = schrutepy.load_schrute()

In [5]:
df.head()

index  season  episode episode_name    director  \
0      1       1        1        Pilot  Ken Kwapis   
1      2       1        1        Pilot  Ken Kwapis   
2      3       1        1        Pilot  Ken Kwapis   
3      4       1        1        Pilot  Ken Kwapis   
4      5       1        1        Pilot  Ken Kwapis   

                                        writer character  \
0  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
1  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
2  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
3  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
4  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   

                                                text  \
0  All right Jim. Your quarterlies look very good...   
1         Oh, I told you. I couldn't close it. So...   
2  So you've come to the master for guidance? Is ...   
3         Actually, you called me in here, but yeah.   
4    All right. Well, let me show you how it's done.   

                                    text_w_direction  
0  All right Jim. Your quarterlies look very good...  
1         Oh, I told you. I couldn't close it. So...  
2  So you've come to the master for guidance? Is ...  
3         Actually, you called me in here, but yeah.  
4    All right. Well, let me show you how it's done.

In [6]:
df.episode_name.value_counts()

The Delivery (Parts 1&2)               625
Classy Christmas (Parts 1&2)           598
Niagara (Parts 1&2)                    552
Dunder Mifflin Infinity (Parts 1&2)    551
Launch Party (Parts 1&2)               545
                                      ... 
Job Fair                               188
Business School                        185
Phyllis' Wedding                       180
Gay Witch Hunt                         141
The Banker                             131
Name: episode_name, Length: 186, dtype: int64

In [7]:
def all_episodes(df):
    seasons = df.season.unique()
    
    for season in seasons:
        print()
        print(season)
        
        print(df[df.season==season].episode.unique())

In [8]:
all_episodes(df)


1
[1 2 3 4 5 6]

2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

3
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 19 20 21 22 23 24]

4
[ 1  3  5  7  9 10 11 12 13 14 15 16 17 18]

5
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 21 22 23 24 25 26
 27 28]

6
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26]

7
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18 19 20 21 22 23 24 25]

8
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

9
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 24]


In [9]:
df[df.episode_name.str.lower().str.contains('parts 1&2')].episode_name.unique()

array(['A Benihana Christmas (Parts 1&2)', 'The Job (Parts 1&2)',
       'Fun Run (Parts 1&2)', 'Dunder Mifflin Infinity (Parts 1&2)',
       'Launch Party (Parts 1&2)', 'Money (Parts 1&2)',
       'Goodbye, Toby (Parts 1&2)', 'Weight Loss (Parts 1&2)',
       'Stress Relief (Parts 1&2)', 'Niagara (Parts 1&2)',
       'The Delivery (Parts 1&2)', 'Classy Christmas (Parts 1&2)',
       'Search Committee (Parts 1&2)'], dtype=object)

# Clean data

### Clean writer

In [9]:
for name in np.sort(df.writer.unique()):
    print(name)

Aaron Shure
Allison Silverman
Amelie Gillette
Anthony Q. Farrell
B.J. Novak
Brent Forrester
Brent Forrester;Justin Spitzer
Caroline Williams
Carrie Kemper
Charlie Grandy
Dan Greaney
Dan Sterling
Daniel Chun
Daniel Chun;Charlie Grandy
Gene Stupnitsky;Lee Eisenberg
Graham Wagner
Greg Daniels
Greg Daniels;Mindy Kaling
Halsted Sullivan;Warren Lieberstein
Jason Kessler
Jennifer Celotta
Jennifer Celotta;Greg Daniels
Jennifer Celotta;Paul Lieberstein
Jon Vitti
Jonathan Green;Gabe Miller
Jonathan Huges
Justin Spitzer
Larry Willmore
Lee Eisenberg;Gene Stupnitsky
Lee Eisenberg;Gene Stupnitsky;Michael Schur
Lester Lewis
Michael Schur
Michael Schur;Lee Eisenberg;Gene Stupnitsky
Mindy Kaling
Nicki Schwartz-Wright
Owen Ellickson
Paul Lieberstein
Paul Lieberstein;Michael Schur
Peter Ocko
Ricky Gervais;Stephen Merchant
Ricky Gervais;Stephen Merchant;Greg Daniels
Robert Padnick
Ryan Koh
Steve Carell
Steve Hely
Tim McAuliffe
Warren Lieberstein;Halsted Sullivan


In [10]:
def clean_writer(df):
    df.loc[df.writer=='Halsted Sullivan;Warren Lieberstein','writer'] = 'Warren Lieberstein;Halsted Sullivan'
    df.loc[df.writer=='Gene Stupnitsky;Lee Eisenberg','writer'] = 'Lee Eisenberg;Gene Stupnitsky'
    df.loc[df.writer=='Michael Schur;Lee Eisenberg;Gene Stupnitsky','writer'] = 'Lee Eisenberg;Gene Stupnitsky;Michael Schur'
#     df[df.writer==] = 
    
    return df

In [11]:
df = clean_writer(df)

## clean director names

In [12]:
def clean_director(df):
    df.loc[df.director=='Greg Daneils','director'] = 'Greg Daniels'
    df.loc[df.director=='Charles McDougal','director'] = 'Charles McDougall'
    df.loc[df.director=='Claire Scanlong','director'] = 'Claire Scanlon'
    df.loc[df.director=='Ken Wittingham','director'] = 'Ken Whittingham'
    df.loc[df.director=='Paul Lieerstein','director'] = 'Paul Lieberstein'
    df.loc[df.director=='Gene Stupnitsky;Lee Eisenberg','director'] = 'Lee Eisenberg;Gene Stupnitsky'
    return df

In [13]:
df = clean_director(df)

In [14]:
family_name = []
for name in np.sort(df.director.value_counts().index.str.split(' ')):
    family_name.append(name[1])
    
for name in np.sort(family_name):
    print(name)

Abrams
Appel
Arteta
Baumgartner
Blitz
Cantley-Kashima
Carell
Celotta
Chun
Cranston
Daniels
Einhorn
Eisenberg;Gene
Farino
Favreau
Feig
Flender
Forrester
Gates
Gordon
Gordon
Gordon
Gordon;Harold
Grandy
Hardcastle
Heckerling
Helms
Holland
Hudlin
Kaling
Kelada
Kirk
Krasinski
Kwapis
Leiner
Lieberstein
McDougall
Merchant
Miller
Nelli
Novak
Nygard
Peretz
Ramis
Reitman
Rogers
Scanlon
Scott
Sohn
Spiller
Webb
Whedon
Whittingham
Wilson
Zisk


# Create df with episodes properties

In [15]:
def episodes_df(df):
    db = {}
    count = 0
    seasons = df.season.unique()
    
    for season in seasons:
        episodes = df[df.season==season].episode.unique()
        
        for episode in episodes:
            title = df[(df.season==season) & (df.episode==episode)].episode_name.values[0]
            director = df[(df.season==season) & (df.episode==episode)].director.values[0]
            writer = df[(df.season==season) & (df.episode==episode)].writer.values[0]
            
            db[count] = {'season':season,'episode':episode,
                         'title':title,'director':director,
                        'writer':writer}
        
            count += 1
    
    return pd.DataFrame(db).transpose()

In [16]:
df_episode = episodes_df(df)

In [17]:
df_episode.head()

season episode          title         director  \
0      1       1          Pilot       Ken Kwapis   
1      1       2  Diversity Day       Ken Kwapis   
2      1       3    Health Care  Ken Whittingham   
3      1       4   The Alliance     Bryan Gordon   
4      1       5     Basketball     Greg Daniels   

                                        writer  
0  Ricky Gervais;Stephen Merchant;Greg Daniels  
1                                   B.J. Novak  
2                             Paul Lieberstein  
3                                Michael Schur  
4                                 Greg Daniels

In [18]:
df_episode.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 0 to 185
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   season    186 non-null    object
 1   episode   186 non-null    object
 2   title     186 non-null    object
 3   director  186 non-null    object
 4   writer    186 non-null    object
dtypes: object(5)
memory usage: 8.7+ KB


In [19]:
df_episode.to_csv('schrute_episode_list.csv',index=False)

# Prepare dataset

In [20]:
def schrut_prep(df):
    df.drop(columns=['index'], axis=1, inplace=True)

    df.drop(df[df.text_w_direction.isna()].index, axis=0, inplace=True)
    
    df.rename(columns={'episode_name':'title','text_w_direction':'text_w'},inplace=True)
    
    return df

In [21]:
df = schrut_prep(df)

In [22]:
df.head()

season  episode  title    director  \
0       1        1  Pilot  Ken Kwapis   
1       1        1  Pilot  Ken Kwapis   
2       1        1  Pilot  Ken Kwapis   
3       1        1  Pilot  Ken Kwapis   
4       1        1  Pilot  Ken Kwapis   

                                        writer character  \
0  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
1  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
2  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
3  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
4  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   

                                                text  \
0  All right Jim. Your quarterlies look very good...   
1         Oh, I told you. I couldn't close it. So...   
2  So you've come to the master for guidance? Is ...   
3         Actually, you called me in here, but yeah.   
4    All right. Well, let me show you how it's done.   

                                              text_w  
0  All right Jim. Your quarterlies look very good...  
1         Oh, I told you. I couldn't close it. So...  
2  So you've come to the master for guidance? Is ...  
3         Actually, you called me in here, but yeah.  
4    All right. Well, let me show you how it's done.