# Preparation of ratings and series info

data source https://www.kaggle.com/bcruise/the-office-episodes-data?select=the_office_episodes.csv

In [145]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [146]:
ep = pd.read_csv('the_office_episodes.csv')

In [147]:
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   season                 201 non-null    int64  
 1   episode_num_in_season  201 non-null    int64  
 2   episode_num_overall    201 non-null    int64  
 3   title                  201 non-null    object 
 4   directed_by            201 non-null    object 
 5   written_by             201 non-null    object 
 6   original_air_date      201 non-null    object 
 7   prod_code              201 non-null    int64  
 8   us_viewers             201 non-null    float64
dtypes: float64(1), int64(4), object(4)
memory usage: 14.3+ KB


In [148]:
ep.head(10)

season  episode_num_in_season  episode_num_overall              title  \
0       1                      1                    1              Pilot   
1       1                      2                    2      Diversity Day   
2       1                      3                    3        Health Care   
3       1                      4                    4       The Alliance   
4       1                      5                    5         Basketball   
5       1                      6                    6           Hot Girl   
6       2                      1                    7        The Dundies   
7       2                      2                    8  Sexual Harassment   
8       2                      3                    9    Office Olympics   
9       2                      4                   10           The Fire   

       directed_by                                         written_by  \
0       Ken Kwapis  Ricky Gervais & Stephen Merchant and Greg Daniels   
1       Ken Kwapis                                        B. J. Novak   
2  Ken Whittingham                                   Paul Lieberstein   
3     Bryan Gordon                                      Michael Schur   
4     Greg Daniels                                       Greg Daniels   
5   Amy Heckerling                                       Mindy Kaling   
6     Greg Daniels                                       Mindy Kaling   
7       Ken Kwapis                                        B. J. Novak   
8        Paul Feig                                      Michael Schur   
9       Ken Kwapis                                        B. J. Novak   

  original_air_date  prod_code  us_viewers  
0        2005-03-24       1001  11200000.0  
1        2005-03-29       1002   6000000.0  
2        2005-04-05       1006   5800000.0  
3        2005-04-12       1004   5400000.0  
4        2005-04-19       1005   5000000.0  
5        2005-04-26       1003   4800000.0  
6        2005-09-20       2003   9000000.0  
7        2005-09-27       2002   7130000.0  
8        2005-10-04       2004   8300000.0  
9        2005-10-11       2001   7600000.0

In [149]:
rate = pd.read_csv('the_office_imdb.csv')

In [150]:
rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   season             188 non-null    int64  
 1   episode_num        188 non-null    int64  
 2   title              188 non-null    object 
 3   original_air_date  188 non-null    object 
 4   imdb_rating        188 non-null    float64
 5   total_votes        188 non-null    int64  
 6   desc               188 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 10.4+ KB


In [151]:
rate.head()

season  episode_num          title original_air_date  imdb_rating  \
0       1            1          Pilot        2005-03-24          7.4   
1       1            2  Diversity Day        2005-03-29          8.3   
2       1            3    Health Care        2005-04-05          7.7   
3       1            4   The Alliance        2005-04-12          8.0   
4       1            5     Basketball        2005-04-19          8.4   

   total_votes                                               desc  
0         7006  The premiere episode introduces the boss and s...  
1         6902  Michael's off color remark puts a sensitivity ...  
2         5756  Michael leaves Dwight in charge of picking the...  
3         5579  Just for a laugh, Jim agrees to an alliance wi...  
4         6183  Michael and his staff challenge the warehouse ...

In [152]:
def all_episodes(df):
    seasons = df.season.unique()
    
    for season in seasons:
        print()
        print(season)
        
        print(df[df.season==season].episode_num.unique())

In [153]:
all_episodes(rate)


1
[1 2 3 4 5 6]

2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

4
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

6
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

7
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

8
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

9
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# Feature Engineering

## Mark all double series

In [154]:
doubled = ep.title.value_counts()

In [155]:
double_titles = []
for name, FT in zip(doubled.index, doubled):
    if FT==2:
        double_titles.append(name)

In [156]:
double_titles

['Dunder Mifflin Infinity',
 'Goodbye, Toby',
 'A Benihana Christmas',
 'Search Committee',
 'The Job',
 'Weight Loss',
 'Fun Run',
 'Launch Party',
 'Money',
 'A.A.R.M.',
 'Finale',
 'Stress Relief',
 'Classy Christmas']

In [157]:
rate['double'] = 0

for name in double_titles:
    rate.loc[rate.title==name,'double']=1

In [158]:
rate[rate.double==1]

season  episode_num                    title original_air_date  \
37        3           10     A Benihana Christmas        2006-12-14   
50        3           23                  The Job        2007-05-17   
51        4            1                  Fun Run        2007-09-27   
52        4            2  Dunder Mifflin Infinity        2007-10-04   
53        4            3             Launch Party        2007-10-11   
54        4            4                    Money        2007-10-18   
64        4           14            Goodbye, Toby        2008-05-15   
65        5            1              Weight Loss        2008-09-25   
77        5           13            Stress Relief        2009-02-01   
127       7           11         Classy Christmas        2010-12-09   
140       7           24         Search Committee        2011-05-19   
186       9           22                 A.A.R.M.        2013-05-09   
187       9           23                   Finale        2013-05-16   

     imdb_rating  total_votes  \
37           8.8         4791   
50           9.3         5482   
51           8.8         5065   
52           8.3         4174   
53           8.4         4064   
54           8.7         4377   
64           9.4         5577   
65           8.8         4597   
77           9.7        11895   
127          9.0         4190   
140          8.7         3719   
186          9.5         5930   
187          9.8        15245   

                                                  desc  double  
37   Trouble among the members of the party plannin...       1  
50   Michael appoints Dwight as regional manager, a...       1  
51   Michael accidentally runs over Meridith in the...       1  
52   Michael feels threatened when Ryan returns to ...       1  
53   The Dunder Mifflin Infinity website is launchi...       1  
54   As Jan renovates the condo, Michael confronts ...       1  
64   Michael throws an extravagant going-away party...       1  
65   Michael tries to motivate the Scranton branch ...       1  
77   Dwight's too-realistic fire alarm gives Stanle...       1  
127  Michael throws an elaborate Christmas party to...       1  
140  The Scranton branch puts together a search com...       1  
186  Dwight prepares for a marriage proposal and hi...       1  
187  One year later, Dunder Mifflin employees past ...       1

In [159]:
rate[rate.double==1].count()

season               13
episode_num          13
title                13
original_air_date    13
imdb_rating          13
total_votes          13
desc                 13
double               13
dtype: int64

## Renumerate all series following double series

In [160]:
rate[rate.title.str.lower().str.contains('delivery')]

season  episode_num                 title original_air_date  imdb_rating  \
107       6           17  The Delivery: Part 1        2010-03-04          8.4   
108       6           18  The Delivery: Part 2        2010-03-04          8.5   

     total_votes                                               desc  double  
107         3438  Pam goes into labor and Jim is ready to take h...       0  
108         3445  After the baby is born, Pam has trouble gettin...       0

In [161]:
def shift_numeration(db):
    db['episode_shifted'] = db['episode_num']
    
    for season in range(1,10):
        episodes = np.sort(db[db.season==season].episode_num.unique())

        for episode in episodes: 
#             print(season, episode)
            
            if db[(db.season==season) & (db.episode_num==episode)].double.values==1:
                for following in range(episode + 1, max(episodes)+1):
                    old_val = db[(db.season==season) & (db.episode_num==following)].episode_shifted
                    db.loc[(db.season==season) & (db.episode_num==following),'episode_shifted'] = old_val + 1

    return db

In [162]:
rate_n = rate.copy(deep=True)

In [163]:
rate=shift_numeration(rate)

In [164]:
rate[rate.season==3]

season  episode_num                 title original_air_date  imdb_rating  \
28       3            1        Gay Witch Hunt        2006-09-21          9.0   
29       3            2        The Convention        2006-09-28          8.2   
30       3            3              The Coup        2006-10-05          8.5   
31       3            4      Grief Counseling        2006-10-12          8.0   
32       3            5            Initiation        2006-10-19          8.1   
33       3            6                Diwali        2006-11-02          7.9   
34       3            7        Branch Closing        2006-11-09          8.6   
35       3            8            The Merger        2006-11-16          8.7   
36       3            9           The Convict        2006-11-30          8.3   
37       3           10  A Benihana Christmas        2006-12-14          8.8   
38       3           11    Back from Vacation        2007-01-04          8.6   
39       3           12    Traveling Salesmen        2007-01-11          8.6   
40       3           13            The Return        2007-01-18          8.8   
41       3           14          Ben Franklin        2007-02-01          8.0   
42       3           15      Phyllis' Wedding        2007-02-08          8.2   
43       3           16       Business School        2007-02-15          8.9   
44       3           17             Cocktails        2007-02-22          8.5   
45       3           18       The Negotiation        2007-04-05          9.0   
46       3           19       Safety Training        2007-04-12          8.8   
47       3           20        Product Recall        2007-04-26          8.7   
48       3           21  Women's Appreciation        2007-05-03          8.8   
49       3           22           Beach Games        2007-05-10          9.2   
50       3           23               The Job        2007-05-17          9.3   

    total_votes                                               desc  double  \
28         5952  Michael apologizes to Oscar, after he finds ou...       0   
29         4354  Michael and Dwight go to a convention in Phila...       0   
30         4562  Michael is in trouble once again as Jan busts ...       0   
31         4366  Michael takes on the role of office grief coun...       0   
32         4248  Dwight takes former temp Ryan to his beet farm...       0   
33         4443  Michael encourages the entire Scranton branch ...       0   
34         4371  When Jan tells Michael that the Scranton Branc...       0   
35         4558  Jan informs Michael that the Scanton branch of...       0   
36         4564  Michael learns that one of the new employees a...       0   
37         4791  Trouble among the members of the party plannin...       1   
38         4333  Michael isn't supposed to let anyone know that...       0   
39         4371  Dwight does a favor for Angela to keep her fro...       0   
40         4592  Andy does the impossible--he makes everyone in...       0   
41         4246  Michael asks Jim to get a male stripper for Ph...       0   
42         4301  Michael exaggerates the importance of his smal...       0   
43         4994  Michael is a guest speaker for Ryan's business...       0   
44         4251  While Michael and Jan go to their first Dunder...       0   
45         4848  Dwight saves Jim from an attack by Roy, but Dw...       0   
46         4516  Andy returns to the office after weeks of ange...       0   
47         4455  Michael tries to be proactive during a waterma...       0   
48         4519  Phyllis gets flashed in the parking lot, and D...       0   
49         5211  Michael uses "beach day" at Dunder-Mifflin to ...       0   
50         5482  Michael appoints Dwight as regional manager, a...       1   

    episode_shifted  
28                1  
29                2  
30                3  
31                4  
32                5  
33                6  
34                7  
35                8  
36          

In [165]:
all_episodes(rate)


1
[1 2 3 4 5 6]

2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

3
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

4
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

6
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]

7
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

8
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

9
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## Delete one of  "Niagara" and one of  "The delivery" series
those two double series are not doubled in imdb for some reason. Since in schrute dataset they are double, i will merge them. Since this double series have almost the same imdb rating,the merging will not will not introduce significant inaccuracies.  and compute wieighted average imdb rating. 

### niagara

In [166]:
rate[rate.title.str.lower().str.contains('niagara')]

season  episode_num            title original_air_date  imdb_rating  \
94       6            4  Niagara: Part 1        2009-10-08          9.4   
95       6            5  Niagara: Part 2        2009-10-08          9.5   

    total_votes                                               desc  double  \
94         6277  The Office travels to Niagara Falls to celebra...       0   
95         5122  Pam is forced to deal with an embarrassing inj...       0   

    episode_shifted  
94                4  
95                5

In [167]:
rates = rate[rate.title.str.lower().str.contains('niagara')].imdb_rating.values
votes = rate[rate.title.str.lower().str.contains('niagara')].total_votes.values

av = np.dot(rates, votes)/sum(votes)
print(rates, votes, round(av,1))

[9.4 9.5] [6277 5122] 9.4


In [168]:
rate.drop(rate[rate.title=='Niagara: Part 2'].index, axis=0,inplace=True)

In [169]:
rate.loc[rate.title.str.lower().str.contains('niagara'),'title'] = 'Niagara'
rate.loc[rate.title.str.lower().str.contains('niagara'),'double'] = 1

In [170]:
rate[rate.title.str.lower().str.contains('niagara')]

season  episode_num    title original_air_date  imdb_rating  total_votes  \
94       6            4  Niagara        2009-10-08          9.4         6277   

                                                 desc  double  episode_shifted  
94  The Office travels to Niagara Falls to celebra...       1                4

### delivery

In [171]:
rate[rate.title.str.lower().str.contains('delivery')]

season  episode_num                 title original_air_date  imdb_rating  \
107       6           17  The Delivery: Part 1        2010-03-04          8.4   
108       6           18  The Delivery: Part 2        2010-03-04          8.5   

     total_votes                                               desc  double  \
107         3438  Pam goes into labor and Jim is ready to take h...       0   
108         3445  After the baby is born, Pam has trouble gettin...       0   

     episode_shifted  
107               17  
108               18

In [172]:
rates = rate[rate.title.str.lower().str.contains('delivery')].imdb_rating.values
votes = rate[rate.title.str.lower().str.contains('delivery')].total_votes.values

av = np.dot(rates, votes)/sum(votes)
print(rates, votes, round(av,1))

[8.4 8.5] [3438 3445] 8.5


In [173]:
rate.drop(rate[rate.title=='The Delivery: Part 2'].index, axis=0,inplace=True)

In [174]:
rate.loc[rate.title.str.lower().str.contains('delivery'),'double'] = 1
rate.loc[rate.title.str.lower().str.contains('delivery'),'title'] = 'The Delivery'
rate.loc[rate.title.str.lower().str.contains('delivery'),'imdb_rating'] = round(av,1)

In [175]:
rate[rate.title.str.lower().str.contains('delivery')]

season  episode_num         title original_air_date  imdb_rating  \
107       6           17  The Delivery        2010-03-04          8.5   

     total_votes                                               desc  double  \
107         3438  Pam goes into labor and Jim is ready to take h...       1   

     episode_shifted  
107               17

## Mark one more episode as double

In [176]:
rate.loc[(rate.season==9) & (rate.episode_num==16),'double'] = 1

## Create month feature

In [177]:
rate['date'] = pd.to_datetime(rate['original_air_date'])

In [178]:
rate['month'] = rate['date'].apply(lambda date: date.month)

In [179]:
rate

season  episode_num             title original_air_date  imdb_rating  \
0         1            1             Pilot        2005-03-24          7.4   
1         1            2     Diversity Day        2005-03-29          8.3   
2         1            3       Health Care        2005-04-05          7.7   
3         1            4      The Alliance        2005-04-12          8.0   
4         1            5        Basketball        2005-04-19          8.4   
..      ...          ...               ...               ...          ...   
183       9           19     Stairmageddon        2013-04-11          8.0   
184       9           20    Paper Airplane        2013-04-25          8.0   
185       9           21  Livin' the Dream        2013-05-02          9.1   
186       9           22          A.A.R.M.        2013-05-09          9.5   
187       9           23            Finale        2013-05-16          9.8   

     total_votes                                               desc  double  \
0           7006  The premiere episode introduces the boss and s...       0   
1           6902  Michael's off color remark puts a sensitivity ...       0   
2           5756  Michael leaves Dwight in charge of picking the...       0   
3           5579  Just for a laugh, Jim agrees to an alliance wi...       0   
4           6183  Michael and his staff challenge the warehouse ...       0   
..           ...                                                ...     ...   
183         2961  Dwight shoots Stanley with a bull tranquilizer...       0   
184         3040  The employees hold a paper airplane competitio...       0   
185         4448  Dwight becomes regional manager after Andy qui...       0   
186         5930  Dwight prepares for a marriage proposal and hi...       1   
187        15245  One year later, Dunder Mifflin employees past ...       1   

     episode_shifted       date  month  
0                  1 2005-03-24      3  
1                  2 2005-03-29      3  
2                  3 2005-04-05      4  
3                  4 2005-04-12      4  
4                  5 2005-04-19      4  
..               ...        ...    ...  
183               19 2013-04-11      4  
184               20 2013-04-25      4  
185               21 2013-05-02      5  
186               22 2013-05-09      5  
187               24 2013-05-16      5  

[186 rows x 11 columns]

# Add info from schrute dataset

In [180]:
text = pd.read_csv('schrute_episode_list.csv')

In [181]:
text.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   season    186 non-null    int64 
 1   episode   186 non-null    int64 
 2   title     186 non-null    object
 3   director  186 non-null    object
 4   writer    186 non-null    object
dtypes: int64(2), object(3)
memory usage: 7.4+ KB


In [182]:
text.head()

season  episode          title         director  \
0       1        1          Pilot       Ken Kwapis   
1       1        2  Diversity Day       Ken Kwapis   
2       1        3    Health Care  Ken Whittingham   
3       1        4   The Alliance     Bryan Gordon   
4       1        5     Basketball     Greg Daniels   

                                        writer  
0  Ricky Gervais;Stephen Merchant;Greg Daniels  
1                                   B.J. Novak  
2                             Paul Lieberstein  
3                                Michael Schur  
4                                 Greg Daniels

## Compare with SChrute episode list

In [183]:
count = 0
for season in range(1,10):
        episodes = np.sort(rate[rate.season==season].episode_shifted.unique())

        for episode in episodes: 
            print()
            print(season, episode)
            print(rate[(rate.season==season) & (rate.episode_shifted==episode)].title.values)
            
            if len(text[(text.season==season) & (text.episode==episode)]) > 0:
                print(text[(text.season==season) & (text.episode==episode)].title.values)
            else:
                print('---')
                count += 1
                
print(f'{count} mismatchs')


1 1
['Pilot']
['Pilot']

1 2
['Diversity Day']
['Diversity Day']

1 3
['Health Care']
['Health Care']

1 4
['The Alliance']
['The Alliance']

1 5
['Basketball']
['Basketball']

1 6
['Hot Girl']
['Hot Girl']

2 1
['The Dundies']
['The Dundies']

2 2
['Sexual Harassment']
['Sexual Harassment']

2 3
['Office Olympics']
['Office Olympics']

2 4
['The Fire']
['The Fire']

2 5
['Halloween']
['Halloween']

2 6
['The Fight']
['The Fight']

2 7
['The Client']
['The Client']

2 8
['Performance Review']
['Performance Review']

2 9
['E-Mail Surveillance']
['E-Mail Surveilance']

2 10
['Christmas Party']
['Christmas Party']

2 11
['Booze Cruise']
['Booze Cruise']

2 12
['The Injury']
['The Injury']

2 13
['The Secret']
['The Secret']

2 14
['The Carpet']
['The Carpet']

2 15
['Boys and Girls']
['Boys & Girls']

2 16
["Valentine's Day"]
["Valentine's Day"]

2 17
["Dwight's Speech"]
["Dwight's Speech"]

2 18
['Take Your Daughter to Work Day']
['Take Your Daughter to Work Day']

2 19
["Michael's Birt

## add columns from schrute to df

In [184]:
def add_columns_from_schrute(df, text):
    df['director'] = np.nan
    df['writer'] = np.nan
    
    for season in range(1,10):
            episodes = np.sort(rate[rate.season==season].episode_shifted.unique())

            for episode in episodes: 
                director = text[(text.season==season) & (text.episode==episode)].director
                writer = text[(text.season==season) & (text.episode==episode)].writer
                
#                 print(season, episode, director.values)
                
                df.loc[(df.season==season) & (df.episode_shifted==episode),'director'] = director.values
                df.loc[(df.season==season) & (df.episode_shifted==episode),'writer'] = writer.values


    return df

In [185]:
 rate[(rate.season==6) & (rate.episode_shifted==6)]

season  episode_num  title original_air_date  imdb_rating  total_votes  \
96       6            6  Mafia        2009-10-15          7.6         3582   

                                                 desc  double  \
96  Michael meets with an insurance salesman that ...       0   

    episode_shifted       date  month  
96                6 2009-10-15     10

In [186]:
df = rate.copy(deep=True)
df = add_columns_from_schrute(df,text)

In [187]:
df[df.writer.isna()]

Empty DataFrame
Columns: [season, episode_num, title, original_air_date, imdb_rating, total_votes, desc, double, episode_shifted, date, month, director, writer]
Index: []

In [188]:
df[df.director.isna()]

Empty DataFrame
Columns: [season, episode_num, title, original_air_date, imdb_rating, total_votes, desc, double, episode_shifted, date, month, director, writer]
Index: []

# Renaming

In [189]:
df.rename(columns={'episode_shifted':'episode','total_votes':'votes','imdb_rating':'rating'},inplace=True)

# Make director and writer categorical

## Writer

In [190]:
df.writer.value_counts()

Mindy Kaling                                   20
B.J. Novak                                     15
Lee Eisenberg;Gene Stupnitsky                  13
Paul Lieberstein                               13
Brent Forrester                                 9
Greg Daniels                                    9
Justin Spitzer                                  9
Jennifer Celotta                                8
Michael Schur                                   7
Warren Lieberstein;Halsted Sullivan             7
Charlie Grandy                                  7
Aaron Shure                                     6
Daniel Chun                                     5
Robert Padnick                                  4
Owen Ellickson                                  4
Carrie Kemper                                   4
Allison Silverman                               3
Steve Hely                                      3
Dan Sterling                                    2
Jennifer Celotta;Paul Lieberstein               2


In [211]:
writers = ['B.J. Novak', 'Mindy Kaling','Gene Stupnitsky', 'Justin Spitzer', 'Brent Forrester',
       'Jennifer Celotta', 'Michael Schur','Warren Lieberstein','Halsted Sullivan', 'Aaron Shure', 'Daniel Chun',
       'Robert Padnick', 'Owen Ellickson', 'Carrie Kemper','Allison Silverman', 'Steve Hely', 'Lester Lewis', 'Steve Carell',
       'Dan Greaney', 'Jonathan Green','Gabe Miller', 'Anthony Q. Farrell',
       'Graham Wagner', 'Dan Sterling', 'Amelie Gillette','Nicki Schwartz-Wright', 'Jon Vitti',
       'Paul Lieberstein','Ryan Koh', 'Tim McAuliffe','Greg Daniels', 'Ricky Gervais','Stephen Merchant','Lee Eisenberg','Caroline Williams',
       'Jason Kessler', 'Peter Ocko', 'Charlie Grandy',
       'Larry Willmore', 'Jonathan Huges']

In [192]:
for writer in writers:
    writer_no_space = writer.replace(' ',"_")
    df['writer_' + writer_no_space] = 0
    
    for season in range(1,10):
        episodes = np.sort(df[df.season==season].episode.unique())

        for episode in episodes: 
            if writer in df[(df.season==season) & (df.episode==episode)].writer.values[0]:
                df.loc[(df.season==season) & (df.episode==episode),['writer_' + writer_no_space]] = 1

In [212]:
writers = ['writer_' + writer.replace(' ','_') for writer in writers]
writers

['writer_B.J._Novak',
 'writer_Mindy_Kaling',
 'writer_Gene_Stupnitsky',
 'writer_Justin_Spitzer',
 'writer_Brent_Forrester',
 'writer_Jennifer_Celotta',
 'writer_Michael_Schur',
 'writer_Warren_Lieberstein',
 'writer_Halsted_Sullivan',
 'writer_Aaron_Shure',
 'writer_Daniel_Chun',
 'writer_Robert_Padnick',
 'writer_Owen_Ellickson',
 'writer_Carrie_Kemper',
 'writer_Allison_Silverman',
 'writer_Steve_Hely',
 'writer_Lester_Lewis',
 'writer_Steve_Carell',
 'writer_Dan_Greaney',
 'writer_Jonathan_Green',
 'writer_Gabe_Miller',
 'writer_Anthony_Q._Farrell',
 'writer_Graham_Wagner',
 'writer_Dan_Sterling',
 'writer_Amelie_Gillette',
 'writer_Nicki_Schwartz-Wright',
 'writer_Jon_Vitti',
 'writer_Paul_Lieberstein',
 'writer_Ryan_Koh',
 'writer_Tim_McAuliffe',
 'writer_Greg_Daniels',
 'writer_Ricky_Gervais',
 'writer_Stephen_Merchant',
 'writer_Lee_Eisenberg',
 'writer_Caroline_Williams',
 'writer_Jason_Kessler',
 'writer_Peter_Ocko',
 'writer_Charlie_Grandy',
 'writer_Larry_Willmore',
 'writ

In [194]:
df[np.insert(writers,0,'writer')]

writer  writer_B.J._Novak  \
0    Ricky Gervais;Stephen Merchant;Greg Daniels                  0   
1                                     B.J. Novak                  1   
2                               Paul Lieberstein                  0   
3                                  Michael Schur                  0   
4                                   Greg Daniels                  0   
..                                           ...                ...   
183                                 Dan Sterling                  0   
184          Warren Lieberstein;Halsted Sullivan                  0   
185                        Nicki Schwartz-Wright                  0   
186                              Brent Forrester                  0   
187                                 Greg Daniels                  0   

     writer_Mindy_Kaling  writer_Gene_Stupnitsky  writer_Justin_Spitzer  \
0                      0                       0                      0   
1                      0                       0                      0   
2                      0                       0                      0   
3                      0                       0                      0   
4                      0                       0                      0   
..                   ...                     ...                    ...   
183                    0                       0                      0   
184                    0                       0                      0   
185                    0                       0                      0   
186                    0                       0                      0   
187                    0                       0                      0   

     writer_Brent_Forrester  writer_Jennifer_Celotta  writer_Michael_Schur  \
0                         0                        0                     0   
1                         0                        0                     0   
2                         0                        0                     0   
3                         0                        0                     1   
4                         0                        0                     0   
..                      ...                      ...                   ...   
183                       0                        0                     0   
184                       0                        0                     0   
185                       0                        0                     0   
186                       1                        0                     0   
187                       0                        0                     0   

     writer_Warren_Lieberstein  writer_Halsted_Sullivan  ...  \
0                            0                        0  ...   
1                            0                        0  ...   
2                            0                        0  ...   
3                            0                        0  ...   
4                            0                        0  ...   
..                         ...                      ...  ...   
183                          0                        0  ...   
184                          1                        1  ...   
185                          0                        0  ...   
186                          0                        0  ...   
187                          0                        0  ...   

     writer_Greg_Daniels  writer_Ricky_Gervais  writer_Stephen_Merchant  \
0                      1                     1                        1   
1                      0                     0                        0   
2                      0                     0                        0   
3                      0                     0                        0   
4                      1                     0                        0   
..                   ...                   ...                      ...   
183                    0                     0           

## director

In [195]:
df.director.value_counts()[:10]

Greg Daniels         15
Randall Einhorn      15
Paul Feig            14
Ken Kwapis           12
Jeffrey Blitz        11
Ken Whittingham       9
David Rogers          9
Matt Sohn             8
Charles McDougall     7
Paul Lieberstein      7
Name: director, dtype: int64

In [203]:
directors = ['Randall Einhorn', 'Greg Daniels', 'Paul Feig', 'Ken Kwapis',
       'Jeffrey Blitz', 'Ken Whittingham', 'David Rogers', 'Matt Sohn',
       'Charles McDougall', 'Paul Lieberstein', 'B.J. Novak',
       'Brent Forrester', 'Tucker Gates', 'Troy Miller', 'Harold Ramis',
       'Rainn Wilson', 'John Krasinski', 'Steve Carell', 'Jennifer Celotta',
       'Mindy Kaling', 'Ed Helms', 'Julian Farino',
       'Lee Eisenberg','Gene Stupnitsky', 'Victor Nelli Jr.', 'Joss Whedon',
       'Claire Scanlon', 'Dean Holland', 'Rodman Flender', 'Dennie Gordon',
       'Jason Reitman', 'Bryan Gordon', 'Charlie Grandy', 'Miguel Arteta',
       'Jesse Peretz', 'Daniel Chun', 'Eric Appel',
       'Marc Webb', 'Roger Nygard', 'Lee Kirk', 'Amy Heckerling', 'John Scott',
       'Seth Gordon', 'Stephen Merchant', 'Bryan Cranston', 'Reginald Hudlin',
       'Craig Zisk', 'Brian Baumgartner', 'J.J. Abrams', 'Alex Hardcastle',
       'Kelly Cantley-Kashima', 'Michael Spiller', 'Danny Leiner',
       'Asaad Kelada', 'Jon Favreau']

In [197]:
for director in directors:
    director_no_space = director.replace(' ','_')
    df['director_' + director_no_space] = 0
    
    for season in range(1,10):
        episodes = np.sort(df[df.season==season].episode.unique())

        for episode in episodes: 
            if director in df[(df.season==season) & (df.episode==episode)].director.values[0]:
                df.loc[(df.season==season) & (df.episode==episode), 'director_' + director_no_space] = 1

In [204]:
directors = ['director_' + director.replace(' ','_') for director in directors]

In [205]:
df[np.insert(directors,0,'director')]

director  director_Randall_Einhorn  director_Greg_Daniels  \
0         Ken Kwapis                         0                      0   
1         Ken Kwapis                         0                      0   
2    Ken Whittingham                         0                      0   
3       Bryan Gordon                         0                      0   
4       Greg Daniels                         0                      1   
..               ...                       ...                    ...   
183        Matt Sohn                         0                      0   
184     Jesse Peretz                         0                      0   
185    Jeffrey Blitz                         0                      0   
186     David Rogers                         0                      0   
187       Ken Kwapis                         0                      0   

     director_Paul_Feig  director_Ken_Kwapis  director_Jeffrey_Blitz  \
0                     0                    1                       0   
1                     0                    1                       0   
2                     0                    0                       0   
3                     0                    0                       0   
4                     0                    0                       0   
..                  ...                  ...                     ...   
183                   0                    0                       0   
184                   0                    0                       0   
185                   0                    0                       1   
186                   0                    0                       0   
187                   0                    1                       0   

     director_Ken_Whittingham  director_David_Rogers  director_Matt_Sohn  \
0                           0                      0                   0   
1                           0                      0                   0   
2                           1                      0                   0   
3                           0                      0                   0   
4                           0                      0                   0   
..                        ...                    ...                 ...   
183                         0                      0                   1   
184                         0                      0                   0   
185                         0                      0                   0   
186                         0                      1                   0   
187                         0                      0                   0   

     director_Charles_McDougall  ...  director_Reginald_Hudlin  \
0                             0  ...                         0   
1                             0  ...                         0   
2                             0  ...                         0   
3                             0  ...                         0   
4                             0  ...                         0   
..                          ...  ...                       ...   
183                           0  ...                         0   
184                           0  ...                         0   
185                           0  ...                         0   
186                           0  ...                         0   
187                           0  ...                         0   

     director_Craig_Zisk  director_Brian_Baumgartner  director_J.J._Abrams  \
0                      0                           0                     0   
1                      0                           0                     0   
2                      0                           0                     0   
3                      0                           0                     0   
4                      0                           0                     0   
..                   ...                         ...                   ...   
183               

# Delete all unnecessary columns

In [207]:
df.columns

Index(['season', 'episode_num', 'title', 'original_air_date', 'rating',
       'votes', 'desc', 'double', 'episode', 'date',
       ...
       'director_Reginald_Hudlin', 'director_Craig_Zisk',
       'director_Brian_Baumgartner', 'director_J.J._Abrams',
       'director_Alex_Hardcastle', 'director_Kelly_Cantley-Kashima',
       'director_Michael_Spiller', 'director_Danny_Leiner',
       'director_Asaad_Kelada', 'director_Jon_Favreau'],
      dtype='object', length=108)

In [208]:
df.drop(columns=['episode_num','date','original_air_date','desc'],inplace=True)

# Saving

In [209]:
df.head()

season          title  rating  votes  double  episode  month  \
0       1          Pilot     7.4   7006       0        1      3   
1       1  Diversity Day     8.3   6902       0        2      3   
2       1    Health Care     7.7   5756       0        3      4   
3       1   The Alliance     8.0   5579       0        4      4   
4       1     Basketball     8.4   6183       0        5      4   

          director                                       writer  \
0       Ken Kwapis  Ricky Gervais;Stephen Merchant;Greg Daniels   
1       Ken Kwapis                                   B.J. Novak   
2  Ken Whittingham                             Paul Lieberstein   
3     Bryan Gordon                                Michael Schur   
4     Greg Daniels                                 Greg Daniels   

   writer_B.J._Novak  ...  director_Reginald_Hudlin  director_Craig_Zisk  \
0                  0  ...                         0                    0   
1                  1  ...                         0                    0   
2                  0  ...                         0                    0   
3                  0  ...                         0                    0   
4                  0  ...                         0                    0   

   director_Brian_Baumgartner  director_J.J._Abrams  director_Alex_Hardcastle  \
0                           0                     0                         0   
1                           0                     0                         0   
2                           0                     0                         0   
3                           0                     0                         0   
4                           0                     0                         0   

   director_Kelly_Cantley-Kashima  director_Michael_Spiller  \
0                               0                         0   
1                               0                         0   
2                               0                         0   
3                               0                         0   
4                               0                         0   

   director_Danny_Leiner  director_Asaad_Kelada  director_Jon_Favreau  
0                      0                      0                     0  
1                      0                      0                     0  
2                      0                      0                     0  
3                      0                      0                     0  
4                      0                      0                     0  

[5 rows x 104 columns]

In [210]:
df.to_csv('imdb.csv',index=False)