# Preparation of dataset with all words
https://towardsdatascience.com/python-text-analysis-with-the-schrutepy-package-234bc70f3916

In [175]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [176]:
# pip install schrutepy

In [177]:
from schrutepy import schrutepy 

In [178]:
df = schrutepy.load_schrute()

In [179]:
df.head()

index  season  episode episode_name    director  \
0      1       1        1        Pilot  Ken Kwapis   
1      2       1        1        Pilot  Ken Kwapis   
2      3       1        1        Pilot  Ken Kwapis   
3      4       1        1        Pilot  Ken Kwapis   
4      5       1        1        Pilot  Ken Kwapis   

                                        writer character  \
0  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
1  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
2  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
3  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
4  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   

                                                text  \
0  All right Jim. Your quarterlies look very good...   
1         Oh, I told you. I couldn't close it. So...   
2  So you've come to the master for guidance? Is ...   
3         Actually, you called me in here, but yeah.   
4    All right. Well, let me show you how it's done.   

                                    text_w_direction  
0  All right Jim. Your quarterlies look very good...  
1         Oh, I told you. I couldn't close it. So...  
2  So you've come to the master for guidance? Is ...  
3         Actually, you called me in here, but yeah.  
4    All right. Well, let me show you how it's done.

In [180]:
df.episode_name.value_counts()

The Delivery (Parts 1&2)               625
Classy Christmas (Parts 1&2)           598
Niagara (Parts 1&2)                    552
Dunder Mifflin Infinity (Parts 1&2)    551
Launch Party (Parts 1&2)               545
Finale                                 522
Goodbye, Toby (Parts 1&2)              516
The Job (Parts 1&2)                    508
Weight Loss (Parts 1&2)                507
A.A.R.M                                501
Moving On                              501
Search Committee (Parts 1&2)           494
Fun Run (Parts 1&2)                    487
A Benihana Christmas (Parts 1&2)       480
The Merger                             474
Money (Parts 1&2)                      452
Stress Relief (Parts 1&2)              416
The Sting                              390
Livin' the Dream                       382
Casino Night                           368
Double Date                            367
Customer Survey                        367
The Injury                             361
Happy Hour 

In [181]:
def all_episodes(df):
    seasons = df.season.unique()
    
    for season in seasons:
        print()
        print(season)
        
        print(df[df.season==season].episode.unique())

In [182]:
all_episodes(df)


1
[1 2 3 4 5 6]

2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

3
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 19 20 21 22 23 24]

4
[ 1  3  5  7  9 10 11 12 13 14 15 16 17 18]

5
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 21 22 23 24 25 26
 27 28]

6
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26]

7
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18 19 20 21 22 23 24 25]

8
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

9
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 24]


In [183]:
df[df.episode_name.str.lower().str.contains('parts 1&2')].episode_name.unique()

array(['A Benihana Christmas (Parts 1&2)', 'The Job (Parts 1&2)',
       'Fun Run (Parts 1&2)', 'Dunder Mifflin Infinity (Parts 1&2)',
       'Launch Party (Parts 1&2)', 'Money (Parts 1&2)',
       'Goodbye, Toby (Parts 1&2)', 'Weight Loss (Parts 1&2)',
       'Stress Relief (Parts 1&2)', 'Niagara (Parts 1&2)',
       'The Delivery (Parts 1&2)', 'Classy Christmas (Parts 1&2)',
       'Search Committee (Parts 1&2)'], dtype=object)

# Clean data

In [184]:
for name in np.sort(df.writer.unique()):
    print(name)

Aaron Shure
Allison Silverman
Amelie Gillette
Anthony Q. Farrell
B.J. Novak
Brent Forrester
Brent Forrester;Justin Spitzer
Caroline Williams
Carrie Kemper
Charlie Grandy
Dan Greaney
Dan Sterling
Daniel Chun
Daniel Chun;Charlie Grandy
Gene Stupnitsky;Lee Eisenberg
Graham Wagner
Greg Daniels
Greg Daniels;Mindy Kaling
Halsted Sullivan;Warren Lieberstein
Jason Kessler
Jennifer Celotta
Jennifer Celotta;Greg Daniels
Jennifer Celotta;Paul Lieberstein
Jon Vitti
Jonathan Green;Gabe Miller
Jonathan Huges
Justin Spitzer
Larry Willmore
Lee Eisenberg;Gene Stupnitsky
Lee Eisenberg;Gene Stupnitsky;Michael Schur
Lester Lewis
Michael Schur
Michael Schur;Lee Eisenberg;Gene Stupnitsky
Mindy Kaling
Nicki Schwartz-Wright
Owen Ellickson
Paul Lieberstein
Paul Lieberstein;Michael Schur
Peter Ocko
Ricky Gervais;Stephen Merchant
Ricky Gervais;Stephen Merchant;Greg Daniels
Robert Padnick
Ryan Koh
Steve Carell
Steve Hely
Tim McAuliffe
Warren Lieberstein;Halsted Sullivan


In [185]:
def clean_writer(df):
    df.loc[df.writer=='Halsted Sullivan;Warren Lieberstein','writer'] = 'Warren Lieberstein;Halsted Sullivan'
    df.loc[df.writer=='Gene Stupnitsky;Lee Eisenberg','writer'] = 'Lee Eisenberg;Gene Stupnitsky'
#     df[df.writer==] = 
    
    return df

In [186]:
df = clean_writer(df)

## clean director names

In [187]:
def clean_director(df):
    df.loc[df.director=='Greg Daneils','director'] = 'Greg Daniels'
    df.loc[df.director=='Charles McDougal','director'] = 'Charles McDougall'
    df.loc[df.director=='Claire Scanlong','director'] = 'Claire Scanlon'
    df.loc[df.director=='Ken Wittingham','director'] = 'Ken Whittingham'
    df.loc[df.director=='Paul Lieerstein','director'] = 'Paul Lieberstein'
    df.loc[df.director=='Gene Stupnitsky;Lee Eisenberg','director'] = 'Lee Eisenberg;Gene Stupnitsky'
    return df

In [188]:
df = clean_director(df)

In [189]:
family_name = []
for name in np.sort(df.director.value_counts().index.str.split(' ')):
    family_name.append(name[1])
    
for name in np.sort(family_name):
    print(name)

Abrams
Appel
Arteta
Baumgartner
Blitz
Cantley-Kashima
Carell
Celotta
Chun
Cranston
Daniels
Einhorn
Eisenberg;Gene
Farino
Favreau
Feig
Flender
Forrester
Gates
Gordon
Gordon
Gordon
Gordon;Harold
Grandy
Hardcastle
Heckerling
Helms
Holland
Hudlin
Kaling
Kelada
Kirk
Krasinski
Kwapis
Leiner
Lieberstein
McDougall
Merchant
Miller
Nelli
Novak
Nygard
Peretz
Ramis
Reitman
Rogers
Scanlon
Scott
Sohn
Spiller
Webb
Whedon
Whittingham
Wilson
Zisk


# Create df with episodes properties

In [190]:
def episodes_df(df):
    db = {}
    count = 0
    seasons = df.season.unique()
    
    for season in seasons:
        episodes = df[df.season==season].episode.unique()
        
        for episode in episodes:
            title = df[(df.season==season) & (df.episode==episode)].episode_name.values[0]
            director = df[(df.season==season) & (df.episode==episode)].director.values[0]
            writer = df[(df.season==season) & (df.episode==episode)].writer.values[0]
            
            db[count] = {'season':season,'episode':episode,
                         'title':title,'director':director,
                        'writer':writer}
        
            count += 1
    
    return pd.DataFrame(db).transpose()

In [191]:
df_episode = episodes_df(df)

In [192]:
df_episode.head()

season episode          title         director  \
0      1       1          Pilot       Ken Kwapis   
1      1       2  Diversity Day       Ken Kwapis   
2      1       3    Health Care  Ken Whittingham   
3      1       4   The Alliance     Bryan Gordon   
4      1       5     Basketball     Greg Daniels   

                                        writer  
0  Ricky Gervais;Stephen Merchant;Greg Daniels  
1                                   B.J. Novak  
2                             Paul Lieberstein  
3                                Michael Schur  
4                                 Greg Daniels

In [193]:
df_episode.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 0 to 185
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   season    186 non-null    object
 1   episode   186 non-null    object
 2   title     186 non-null    object
 3   director  186 non-null    object
 4   writer    186 non-null    object
dtypes: object(5)
memory usage: 8.7+ KB


In [194]:
df_episode.to_csv('schrute_episode_list.csv',index=False)

# Explore empty text

In [84]:
df[df.text.isna()]

index  season  episode   episode_name        director  \
149      150       1        1          Pilot      Ken Kwapis   
345      346       1        2  Diversity Day      Ken Kwapis   
1282    1283       1        6       Hot Girl  Amy Heckerling   
1346    1347       1        6       Hot Girl  Amy Heckerling   
1394    1395       1        6       Hot Girl  Amy Heckerling   
...      ...     ...      ...            ...             ...   
54783  54784       9       24         Finale      Ken Kwapis   
54937  54938       9       24         Finale      Ken Kwapis   
54946  54947       9       24         Finale      Ken Kwapis   
54978  54979       9       24         Finale      Ken Kwapis   
55084  55085       9       24         Finale      Ken Kwapis   

                                            writer   character text  \
149    Ricky Gervais;Stephen Merchant;Greg Daniels         Pam  NaN   
345                                     B.J. Novak         Jim  NaN   
1282                                  Mindy Kaling       Kevin  NaN   
1346                                  Mindy Kaling        Toby  NaN   
1394                                  Mindy Kaling         Pam  NaN   
...                                            ...         ...  ...   
54783                                 Greg Daniels  Bill Hader  NaN   
54937                                 Greg Daniels        Toby  NaN   
54946                                 Greg Daniels         Guy  NaN   
54978                                 Greg Daniels      Rachel  NaN   
55084                                 Greg Daniels         All  NaN   

                     text_w_direction  
149                        [Laughing]  
345                              [/b]  
1282                           [nods]  
1346                 [looks resigned]  
1394                         [smiles]  
...                               ...  
54783  [pulling multiple tissues out]  
54937    [dancing with Pam] [sobbing]  
54946                    [fake cries]  
54978  [speaks in a special language]  
55084                       [screams]  

[374 rows x 9 columns]

In [85]:
df[df.text_w_direction.isna()]

index  season  episode    episode_name      director  \
8813    8814       3        7  Branch Closing  Tucker Gates   
47644  47645       8       23        Turf War   Daniel Chun   
47645  47646       8       23        Turf War   Daniel Chun   
47646  47647       8       23        Turf War   Daniel Chun   
53239  53240       9       19   Stairmageddon     Matt Sohn   

                                    writer character text text_w_direction  
8813                         Michael Schur    Dwight  NaN              NaN  
47644  Warren Lieberstein;Halsted Sullivan    Angela  NaN              NaN  
47645  Warren Lieberstein;Halsted Sullivan    Angela  NaN              NaN  
47646  Warren Lieberstein;Halsted Sullivan    Angela  NaN              NaN  
53239                         Dan Sterling      Andy  NaN              NaN

# Prepare dataset

In [103]:
def schrut_prep(df):
    df.drop(columns=['index'], axis=1, inplace=True)

    df.drop(df[df.text_w_direction.isna()].index, axis=0, inplace=True)
    
    df.rename(columns={'episode_name':'title','text_w_direction':'text_w'},inplace=True)
    
    return df

In [108]:
df = schrut_prep(df)

In [109]:
df.head()

season  episode  title    director  \
0       1        1  Pilot  Ken Kwapis   
1       1        1  Pilot  Ken Kwapis   
2       1        1  Pilot  Ken Kwapis   
3       1        1  Pilot  Ken Kwapis   
4       1        1  Pilot  Ken Kwapis   

                                        writer character  \
0  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
1  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
2  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   
3  Ricky Gervais;Stephen Merchant;Greg Daniels       Jim   
4  Ricky Gervais;Stephen Merchant;Greg Daniels   Michael   

                                              text_w  \
0  All right Jim. Your quarterlies look very good...   
1         Oh, I told you. I couldn't close it. So...   
2  So you've come to the master for guidance? Is ...   
3         Actually, you called me in here, but yeah.   
4    All right. Well, let me show you how it's done.   

                                    text_w_direction  
0  All right Jim. Your quarterlies look very good...  
1         Oh, I told you. I couldn't close it. So...  
2  So you've come to the master for guidance? Is ...  
3         Actually, you called me in here, but yeah.  
4    All right. Well, let me show you how it's done.